title: PLUGIN_ADMIN.DEFAULT
'@extends':
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:
      fields:
        options:
          fields:
            publishing:
              fields:

                header.login.visibility_requires_access:
                  ordering@: 1
                  type: toggle
                  toggleable: true
                  label: Visibility Requires Access
                  highlight: 1
                  default: false
                  options:
                    true: Yes
                    false: No
                  validate:
                    type: bool

                header.access.site:
                  ordering@: 2
                  type: checkboxes
                  toggleable: true
                  label: Groups
                  help: Groups
                  default: false
                  ignore_empty: true
                  data-options@: '\Grav\Common\User\Group::groupNames'
                  use: keys
                  validate:
                    type: array
